name: ci_bash
env:
  br : "$github.sha"

on:
  push:
    branches: 
      - '*'
      - 'main'
      
jobs:
  pushing_to_docker:
     runs-on: ubuntu-latest
     steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: build
        run: docker build .
        
      - name: tag
        run: docker tag eugene191/flask32 eugene191/mydockerhubflask:${{ env.br }}"
        
      - name: login
        uses: docker/login-action@v2
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
         
      - name: push
        run: docker push eugene191/mydockerhubflask:${{ env.br }}"
