# letter i have to add branches. Mabe I can use branches-ignore
name: ci_bash

on:
  push:
    # branches: 
    # branches-ignore: 
jobs:
  pushing_to_docker:
     runs-on: ubuntu-latest
     steps:
       - name: pulling-image
         run: docker pull eugene191/flask32
       - name: runing_cont
         run: docker run -d eugene191/flask32
       - name: commit_tag
         run: |
               docker stop $(docker ps -a -q)
 
