# letter i have to add branches. Mabe I can use branches-ignore
name: ci_bash

on:
  push:
    # branches: 
    # branches-ignore: 
jobs:
  pushing_to_docker:
     runs-on: ubuntu-latest
     steps:
       - name: pulling-image
         run: docker pull eugene191/flask32
       - name: runing_cont
         run: docker run -d eugene191/flask32
       - name: commit_tag
         run: |
               docker stop $(docker ps -a -q)
 
 
 
 
 
 
 
 
 
 # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
