name: ci_bash

on:
  push:
    branches: 
      - '*'
      - 'main'
      
jobs:
  pushing_to_docker:
     runs-on: ubuntu-latest
     steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: build
        run: docker build .
        
      - name: cut
        run: mynumber=$(echo $github.sha | cut -c1-4)
        
      - name: tag
        run: docker tag eugene191/flask32 eugene191/mydockerhubflask:$mynumber
        
      - name: login
        uses: docker/login-action@v2
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
         
      - name: push
        run: docker push eugene191/mydockerhubflask:$mynumber
