name: ci_bash

on:
  push:
    branches: 
      - '*'
      - '!main'
      
jobs:
  pushing_to_docker:
     runs-on: ubuntu-latest
     steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 4
      - run: echo $SHA
        env: 
          SHA: ${{ steps.short-sha.outputs.sha }}
      - run: echo $SHA
        env: 
          SHA: ${{ env.SHA }}
        
      - name: build
        run: | 
         docker build . /
         docker tag eugene191/flask32 eugene191/mydockerhubflask:${{ env.SHA }} /
         
      - name: login
        uses: docker/login-action@v2
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
         
      - name: push
        run: docker push eugene191/mydockerhubflask:${{ env.SHA }}
